FROM ubuntu:20.04

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get -y update
RUN apt-get -y install libgl1-mesa-dev

RUN apt-get -y install git
RUN git clone https://github.com/OhMyBuggg/Social-Distancing-AI.git

RUN apt-get install -y vim

RUN apt-get install -y python3
RUN apt-get install -y python3-pip

RUN pip install opencv-python
RUN pip install numpy
RUN pip install argparse==1.4.0

RUN apt-get install -y libgtk2.0-dev
RUN apt-get install wget

RUN cd Social-Distancing-AI && \
    wget https://pjreddie.com/media/files/yolov3.weights && \
    mv yolov3.weights ./models/

