FROM nvidia/cuda:11.4.3-runtime-ubuntu20.04

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get -y update
RUN apt-get -y install git
RUN git clone https://github.com/OhMyBuggg/Social-Distancing-AI.git

RUN apt-get install -y python3
RUN apt-get install -y python3-pip

RUN pip install opencv-python==4.2.0.34
RUN pip install numpy==1.17.5
RUN pip install argparse==1.4.0

RUN apt-get install -y libgtk2.0-dev
RUN apt-get install wget

RUN cd Social-Distancing-AI && \
    wget https://pjreddie.com/media/files/yolov3.weights && \
    mv yolov3.weights ./models/